config/routes.rb
Rails.application.routes.draw do
  resources :productos
  devise_for :users
  root 'pages#index'

  get 'pages/index'
  get 'productos/buscar'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :producto

end

app/models/producto.rb
require 'elasticsearch/model'

class Producto < ActiveRecord::Base
  has_many :galleries
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :nombre, analyzer: 'spanish'
      indexes :descripcion, analyzer: 'spanish'
    end
  end

  def buscar
  end

end

# Delete the previous articles index in Elasticsearch
Producto.__elasticsearch__.client.indices.delete index: Producto.index_name rescue nil

# Create the new index with the new mapping
Producto.__elasticsearch__.client.indices.create \
  index: Producto.index_name,
  body: { settings: Producto.settings.to_hash, mappings: Producto.mappings.to_hash }

# Index all article records from the DB to Elasticsearch
Producto.import

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_product

  def index
  end

  private

    def set_product
      @producto = Producto.new
    end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  before_action :set_all_products

  # GET /productos
  # GET /productos.json
  def index
  end

  def buscar
    if params[:producto][:buscar].nil?
      @productos = []
    else
      @productos = Producto.search params[:producto][:buscar]
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)
    create_gallery
    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    create_gallery
    debugger
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    def create_gallery
      params[:producto][:gallery].each do |key, value|
        @producto.galleries << Gallery.create(image: value)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :cantidad, gallery_attributes: [:image])
    end

    def set_all_products
      @productos = Producto.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <img src="/assets/tech-brain-logo.jpg" alt="Brain Logo" class="logo img-responsive"/>
      <% end %>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Catálogo de productos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if params[:controller] != 'productos' || params[:id] == nil %>
              <li><%= link_to 'Nuevo Producto', new_producto_path %></li>
              <li><%= link_to 'Mostrar catálogo', productos_path %></li>
            <% elsif params[:id] != nil %>
                <li><%= link_to 'Nuevo Producto', new_producto_path %></li>
                <li><%= link_to 'Mostrar Catálogo', productos_path %></li>
                <li><%= link_to 'Editar Producto', edit_producto_path(@producto) %></li>
                <li><%= link_to 'Eliminar Producto', @producto, method: :delete, data: { confirm: 'Are you sure?' } %></li>

            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <%= form_for @producto, url: productos_buscar_path do |f| %>
            <%= f.label :buscar %>
            <%= f.text_field :buscar, class: 'form-control', autofocus: true, placeholder: 'Buscar productos' %>
            <%= f.submit 'Buscar', class: 'btn btn-default' %>
          <% end %>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Opciones de sesión<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user.nil? %>
              <li>
                <%= link_to 'Ingresa', new_user_session_path %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to 'Regístrate', new_user_registration_path %>
              </li>
            <% else %>
            <li>
              <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to 'Cambia tu contraseña', edit_user_registration_path %>
            </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examenfinal</title>
  <%= stylesheet_link_tag    'bootstrap', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'bootstrap' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'navbar' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <%= yield %>
    <p class="alert"><%= alert %></p>
  </div>

  </ul>
</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>

  <%= f.fields_for :gallery do |images| %><br>
    <div class="field">
      <%= images.label :primera %><br>
      <%= images.file_field '1', id: 'primera' %>
    </div>

    <div class="field">
      <%= images.label :segunda %><br>
      <%= images.file_field '2', id: 'segunda' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th>Primer imagen</th>
      <th>Segunda imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.cantidad %></td>

        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @producto.cantidad %>
</p>

<p>
  <strong>Imágenes</strong>
    <%= image_tag @producto.galleries.first.image_url(:medium) %>
    <%= image_tag @producto.galleries.second.image_url(:medium) %>

</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>